# Generated by Django 4.2 on 2023-05-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=255)),
                ('denotion', models.CharField(max_length=255)),
                ('ein', models.CharField(max_length=10)),
                ('rule', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='adjective_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Adverb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adverb', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='adverb_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Conjunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('articles', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='conjunction_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=255)),
                ('nominative', models.CharField(max_length=255)),
                ('accusative', models.CharField(max_length=255)),
                ('dative', models.CharField(max_length=255)),
                ('genitive', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('n1e', models.CharField(max_length=255)),
                ('n2e', models.CharField(max_length=255)),
                ('n1', models.CharField(max_length=255)),
                ('n2', models.CharField(max_length=255)),
                ('a1e', models.CharField(max_length=255)),
                ('a2e', models.CharField(max_length=255)),
                ('a1', models.CharField(max_length=255)),
                ('a2', models.CharField(max_length=255)),
                ('d1e', models.CharField(max_length=255)),
                ('d2e', models.CharField(max_length=255)),
                ('d1', models.CharField(max_length=255)),
                ('d2', models.CharField(max_length=255)),
                ('g1e', models.CharField(max_length=255)),
                ('g2e', models.CharField(max_length=255)),
                ('g1', models.CharField(max_length=255)),
                ('g2', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='noun_images')),
            ],
        ),
        migrations.CreateModel(
            name='Preposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preposition', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=255)),
                ('case', models.CharField(max_length=255)),
                ('target1', models.CharField(max_length=255)),
                ('target2', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='preposition_images')),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=255)),
                ('ich', models.CharField(max_length=255)),
                ('du', models.CharField(max_length=255)),
                ('es', models.CharField(max_length=255)),
                ('wir', models.CharField(max_length=255)),
                ('ihr', models.CharField(max_length=255)),
                ('sie', models.CharField(max_length=255)),
                ('target1', models.CharField(max_length=255)),
                ('target2', models.CharField(max_length=255)),
                ('t1', models.CharField(max_length=255)),
                ('t2', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='verb_images')),
            ],
        ),
        migrations.CreateModel(
            name='SplitVerb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=255)),
                ('english', models.CharField(max_length=255)),
                ('ich', models.CharField(max_length=255)),
                ('du', models.CharField(max_length=255)),
                ('es', models.CharField(max_length=255)),
                ('wir', models.CharField(max_length=255)),
                ('ihr', models.CharField(max_length=255)),
                ('sie', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('target2', models.CharField(max_length=255)),
                ('cases', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='verb_images')),
                ('prepositions', models.ManyToManyField(to='dbmgmt.preposition')),
            ],
        ),
    ]
