# Generated by Django 4.2 on 2023-05-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adjective',
            old_name='rule',
            new_name='adjective',
        ),
        migrations.RenameField(
            model_name='preposition',
            old_name='case',
            new_name='cases',
        ),
        migrations.AddField(
            model_name='conjunction',
            name='conjunction',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
