# Generated by Django 4.2 on 2023-05-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmgmt', '0003_alter_adjective_denotion_alter_adjective_ein_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjunction',
            name='articles',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preposition',
            name='preposition',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
