# Generated by Django 4.2 on 2023-05-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmgmt', '0004_alter_conjunction_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noun',
            name='targets',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
