# Generated by Django 4.2 on 2023-05-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmgmt', '0005_noun_targets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noun',
            name='targets',
        ),
        migrations.AddField(
            model_name='verb',
            name='isMaster',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
