# Generated by Django 4.2 on 2023-05-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmgmt', '0006_remove_noun_targets_verb_ismaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noun',
            name='noun',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
